## Reglas HTTP compartidas

# Compresion gzip para contenido de texto
gzip on;
gzip_vary on;
gzip_proxied any;
gzip_comp_level 6;
gzip_buffers 16 8k;
gzip_http_version 1.1;
gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

# Tamano maximo de subida (ajusta si necesitas)
client_max_body_size 10M;
