upstream next_app {
  server 127.0.0.1:3000;
}

server {
  listen 80;
  server_name hennyfeliz.site portfolio.hennyfeliz.site;

  location / {
    proxy_pass http://next_app;
    include conf.d/proxy_common.conf;
  }
}

# HTTPS (habilita cuando tengas certificados validos)
# server {
#   listen 443 ssl http2;
#   server_name hennyfeliz.site portfolio.hennyfeliz.site;
#
#   ssl_certificate      ssl/hennyfeliz.site/fullchain.pem;
#   ssl_certificate_key  ssl/hennyfeliz.site/privkey.pem;
#
#   # Seguridad basica
#   ssl_protocols TLSv1.2 TLSv1.3;
#   ssl_prefer_server_ciphers on;
#
#   location / {
#     proxy_pass http://next_app;
#     include conf.d/proxy_common.conf;
#   }
# }
